### ISSUE TITLE
モジュール化するとAttributeError: 'NoneType' object has no attribute 'get' となり使えない

### ISSUE THREAD

**Issue by nesosuke** [nesosuke/BookCollectionService#3]
openbd.jpのAPIを利用してISBNから書籍情報を取得するスクリプト [`getinfo.py`]( https://github.com/nesosuke/BookCollectionService/blob/8e0f08613a78d07642b5c5c5f9be14829c4016ea/getinfo.py )を作った。

``` getinfo.py
#!/usr/bin/python3
import requests as req
import sys

def search(isbn):
    BookInfo = req.get('https://api.openbd.jp/v1/get?isbn=' + str(isbn)).json()[0].get('summary')
    return BookInfo

if __name__ == '__main__':
    isbn = sys.argv[1]
    BookInfo = search(isbn)
    print(BookInfo)
```

単体で `$ python3 getinfo.py 9784101010137` とすると
```
{'isbn': '9784101010137', 'title': 'こころ', 'volume': '', 'series': '', 'publisher': '新潮
社', 'pubdate': '2004-03', 'cover': 'https://cover.openbd.jp/9784101010137.jpg', 'author': '夏目漱石／著 小林勝／著 伊藤昇／著'}
``` 
が返ってきて期待通りの動作をするが、これをモジュールとして呼び出したテスト用のスクリプト [`a.py`]( https://github.com/nesosuke/BookCollectionService/blob/8e0f08613a78d07642b5c5c5f9be14829c4016ea/a.py ) では
``` a.py
import getinfo
import sys

a = sys.argv[0]
b = getinfo.search(a)

print(b)
```
同じく `$ python3 a.py 9784101010137` しても
```
Traceback (most recent call last):
  File "a.py", line 5, in <module>
    b = getinfo.search(a)
  File "/mnt/c/Users/neso/git/bookcollectionservice/getinfo.py", line 6, in search
    BookInfo = req.get('https://api.openbd.jp/v1/get?isbn=' + str(isbn)).json()[0].get('summary')
AttributeError: 'NoneType' object has no attribute 'get'
```
となり単体のときと同じように動かない :(

**Comment by nesosuke** [comment]
`sys.argv[0]`では何も取れてないですよ  `argv[1]`でかいけつ.  
sovled at https://github.com/nesosuke/BookCollectionService/commit/1374dc98fb5032c51cd32103cb4823aa072e08a3

**Comment by nesosuke** [comment]
原因
<https://docs.python.org/3/library/sys.html>
```
sys.argv
Pythonスクリプトに渡されたコマンドライン引数のリスト。 argv[0] はスクリプトの名前となります
```
